version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
           git config --global user.name "Synchroz"
           git config --global user.email "juliyanto1071@student.untan.ac.id"
           git config --global color.ui false
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} script
           bash script/.circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
